config/routes.rb
Sampleblog::Application.routes.draw do

  resources :posts

  get "welcome/index"

   root to: 'posts#index'

  resources :posts do
    resources :comments
  end

  get 'tweets/:id' => 'posts#tweets', :as => 'tweets'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body))
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :text))

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def tweets
		@post = Post.find(params[:id])
		@tweets = Twitter.search("#{@post.title} -rt", :count => 5, :result_type => "recent").results.map
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
	<strong><%= comment.commenter %></strong> says,
</p>
<p>
	<em>"<%= comment.body %>"</em>
</p>
<p>
	<%= link_to 'Delete', [comment.post, comment],
					method: :delete, data: { confirm: "Are you sure?"},
					type: "button", class: "btn btn-mini btn-danger" %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
  	<%= f.label :commenter %><br />
  	<%= f.text_field :commenter %>
  </p>
  <p>
  	<%= f.label :body %><br />
  	<%= f.text_field :body %>
  </p>
  <p>
  	<%= f.submit 'Create Comment', class: "btn btn-success" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sampleblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Submit', class: "btn btn-success" %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path, type: "button", class: "btn btn-primary" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
	<h2><%= link_to post.title, post_path(post) %></h2>
	<p><%= post.text %></p>
<% end %>
<%= link_to "New Post", new_post_path, type: "button", class: "btn btn-success" %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div ng-app>
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.text_field :title, placeholder: 'Title', :'ng-model' => 'Title' %>
  </p>

  <p>
    <%= f.text_area :text, placeholder: 'Text', :'ng-model' => 'Text' %>
  </p>

  <h2>{{Title}}</h2>
  <p>{{Text}}</p>	
  <br>
  <p>
    <%= f.submit 'Submit', class: "btn btn-success" %>
  </p>
<% end %>
</div>
<%= link_to "Back", posts_path, type: "button", class: "btn btn-primary" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>	<%= @post.text %></p>

<!-- Edit button to trigger modal -->
	<button class="btn btn-warning" data-toggle="modal" data-target="#editModal">
	  Edit
	</button>

	<!-- Modal -->
	<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" id="editModalLabel"> <%= @post.title %> </h4>
	      </div>
	      <%= form_for @post do |f| %>
	      <div class="modal-body">
	    	  <p>
			    <%= f.text_area :text %>
			  </p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= f.submit 'Save Changes', class: "btn btn-primary" %>
	      </div>
	      <% end %>
	    </div>
	  </div>
	</div>
<%= link_to 'Delete', post_path(@post),
						method: :delete, data: { confirm: "Are you sure?"},
						type: "button", class: "btn btn-danger" %>
<br/>
<br/>
<%= link_to "Related Tweets", tweets_path(@post), type: "button", class: "btn btn-primary" %>


<h3>Comments</h3>
<%= render @post.comments %>

<h3>Add a comment:</h3>
<%= render "comments/form" %>
<%= link_to 'Back to Posts', posts_path, type: "button", class: "btn btn-primary" %>

app/views/posts/tweets.html.erb
<h1>Related Tweets</h1>

<%= @tweets.each do |tweet| %>
	<p><strong><%= tweet.from_user %></strong> says,</p>
	<p><em>"<%= tweet.text %>"</em></p>
	<br>
<% end %>

<br>
<%= link_to 'Back to Posts', posts_path, type: "button", class: "btn btn-primary" %>

app/views/welcome/index.html.erb
<h1>Hello, World</h1>
<%= link_to "Enter", posts_path, type: "button", class: "btn btn-primary" %>